### ISSUE TITLE
Service `web` in scenario.yml starts before POSTGRES_PORT is set

### ISSUE THREAD

**Issue by elimence** [lgiordani/flask_project_setup#4]
Thanks for the great tutorial, it's super helpful.

I got the error below when running the first scenario, and looking at how the code in manage.py is structured:

`cmdline = docker_compose_cmdline('up -d')` starts both database and web services, before the port is set a few lines down
`port = out.decode('utf-8').replace('\n', '').split(':')[1]`
`os.environ['POSTGRES_PORT'] = port`

```
* Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 321, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 406, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/opt/code/wsgi.py", line 5, in <module>
    app = create_app(os.environ['FLASK_CONFIG'])
  File "/opt/code/application/app.py", line 10, in create_app
    app.config.from_object(config_module)
  File "/usr/local/lib/python3.9/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/utils.py", line 865, in import_string
    __import__(import_name)
  File "/opt/code/application/config.py", line 6, in <module>
    class Config(object):
  File "/opt/code/application/config.py", line 12, in Config
    port = os.environ['POSTGRES_PORT']
  File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'POSTGRES_PORT'
```

**Comment by lgiordani** [comment]
Hey, sorry for not answering to this. I'll have a look at it soon!

**Comment by elimence** [comment]
Thanks :)
